[package]
name = "tcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
tokio-util = "0.7.17"
uuid = { version = "1", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = "0.3"
random_name_generator = "0.3.6"
colored = "2.1"